alter table T_FF_RT_PROCINST_VAR drop constraint FKD79C420D7AF471D8;
alter table T_FF_RT_WORKITEM drop constraint FK4131554DE2527DDC;
drop table T_FF_DF_WORKFLOWDEF if exists;
drop table T_FF_HIST_TRACE if exists;
drop table T_FF_RT_PROCESSINSTANCE if exists;
drop table T_FF_RT_PROCINST_VAR if exists;
drop table T_FF_RT_TASKINSTANCE if exists;
drop table T_FF_RT_TOKEN if exists;
drop table T_FF_RT_WORKITEM if exists;
create table T_FF_DF_WORKFLOWDEF (ID varchar(50) not null, definition_type varchar(50) not null, PROCESS_ID varchar(100) not null, NAME varchar(100) not null, DISPLAY_NAME varchar(128), DESCRIPTION varchar(1024), VERSION integer not null, STATE bit not null, UPLOAD_USER varchar(50), UPLOAD_TIME timestamp, PUBLISH_USER varchar(50), PUBLISH_TIME timestamp, PROCESS_CONTENT longvarchar, primary key (ID));
create table T_FF_HIST_TRACE (ID varchar(50) not null, PROCESSINSTANCE_ID varchar(50) not null, STEP_NUMBER integer not null, MINOR_NUMBER integer not null, TYPE varchar(15) not null, EDGE_ID varchar(100), FROM_NODE_ID varchar(100) not null, TO_NODE_ID varchar(100) not null, primary key (ID));
create table T_FF_RT_PROCESSINSTANCE (ID varchar(50) not null, PROCESS_ID varchar(100) not null, VERSION integer not null, NAME varchar(100), DISPLAY_NAME varchar(128), STATE integer not null, SUSPENDED bit not null, CREATOR_ID varchar(50), CREATED_TIME timestamp, STARTED_TIME timestamp, EXPIRED_TIME timestamp, END_TIME timestamp, PARENT_PROCESSINSTANCE_ID varchar(50), PARENT_TASKINSTANCE_ID varchar(50), primary key (ID));
create table T_FF_RT_PROCINST_VAR (PROCESSINSTANCE_ID varchar(50) not null, VALUE varchar(255), NAME varchar(255) not null, primary key (PROCESSINSTANCE_ID, NAME));
create table T_FF_RT_TASKINSTANCE (ID varchar(50) not null, BIZ_TYPE varchar(250) not null, TASK_ID varchar(300) not null, ACTIVITY_ID varchar(200) not null, NAME varchar(100) not null, DISPLAY_NAME varchar(128), STATE integer not null, SUSPENDED bit not null, TASK_TYPE varchar(10), CREATED_TIME timestamp not null, STARTED_TIME timestamp, EXPIRED_TIME timestamp, END_TIME timestamp, ASSIGNMENT_STRATEGY varchar(10), PROCESSINSTANCE_ID varchar(50) not null, PROCESS_ID varchar(100) not null, VERSION integer not null, TARGET_ACTIVITY_ID varchar(100), FROM_ACTIVITY_ID varchar(600), STEP_NUMBER integer not null, CAN_BE_WITHDRAWN bit not null, primary key (ID));
create table T_FF_RT_TOKEN (ID varchar(50) not null, ALIVE bit not null, VALUE integer not null, NODE_ID varchar(200) not null, PROCESSINSTANCE_ID varchar(50) not null, STEP_NUMBER integer not null, FROM_ACTIVITY_ID varchar(100), primary key (ID));
create table T_FF_RT_WORKITEM (ID varchar(50) not null, STATE integer not null, CREATED_TIME timestamp not null, CLAIMED_TIME timestamp, END_TIME timestamp, ACTOR_ID varchar(50), COMMENTS varchar(1024), TASKINSTANCE_ID varchar(50) not null, primary key (ID));
create index IDX_TRACE_PROCINSTID on T_FF_HIST_TRACE (PROCESSINSTANCE_ID);
alter table T_FF_RT_PROCINST_VAR add constraint FKD79C420D7AF471D8 foreign key (PROCESSINSTANCE_ID) references T_FF_RT_PROCESSINSTANCE;
alter table T_FF_RT_WORKITEM add constraint FK4131554DE2527DDC foreign key (TASKINSTANCE_ID) references T_FF_RT_TASKINSTANCE;
