alter table T_BIZ_GD_TASKINSTANCE drop foreign key FKF0F6F985D06C779D;
alter table T_BIZ_LOAN_TASKINSTANCE drop foreign key FKCBD3CE1240A045E2;
drop table if exists T_BIZ_GD_TASKINSTANCE;
drop table if exists T_BIZ_LOANINFO;
drop table if exists T_BIZ_LOAN_APPROVEINFO;
drop table if exists T_BIZ_LOAN_TASKINSTANCE;
drop table if exists T_Biz_TradeInfo;
drop table if exists T_FF_RT_TASKINSTANCE;
drop table if exists T_SECU_DEPARTMENT;
drop table if exists T_SECU_RESOURCE;
drop table if exists T_SECU_ROLE;
drop table if exists T_SECU_ROLE_RESOURCE;
drop table if exists T_SECU_USER;
drop table if exists T_SECU_USER_ROLE;
create table T_BIZ_GD_TASKINSTANCE (TASKINSTANCE_ID varchar(50) not null, SN varchar(255), GOODS_NAME varchar(255), QUANTITY bigint, CUSTOMER_NAME varchar(255), primary key (TASKINSTANCE_ID));
create table T_BIZ_LOANINFO (ID varchar(50) not null, SN varchar(50) not null unique, APPLICANT_NAME varchar(50) not null, APPLICANT_ID varchar(50) not null, ADDRESS text not null, SALARY integer not null, LOAN_VALUE integer not null, RETURN_DATE varchar(10) not null, LOANTELLER varchar(50) not null, APP_INFO_INPUT_DATE datetime not null, SALARY_IS_REAL bit, CREDIT_STATUS bit, RISK_FLAG bit, RISK_EVALUATOR varchar(50), RISK_INFO_INPUT_DATE datetime, DECISION bit, examinerList varchar(128), approverList varchar(128), opponentList varchar(128), LEND_MONEY_INFO text, LEND_MONEY_OFFICER varchar(50), LEND_MONEY_INFO_INPUT_TIME datetime, REJECT_INFO text, REJECT_INFO_INPUT_TIME datetime, primary key (ID));
create table T_BIZ_LOAN_APPROVEINFO (ID varchar(50) not null, SN varchar(50) not null, approver varchar(50) not null, decision bit, detail varchar(50), primary key (ID));
create table T_BIZ_LOAN_TASKINSTANCE (TASKINSTANCE_ID varchar(50) not null, SN varchar(255), APPLICANT_NAME varchar(255), LOAN_VALUE integer, RISK_FLAG bit, DECISION bit, primary key (TASKINSTANCE_ID));
create table T_Biz_TradeInfo (ID varchar(50) not null, SN varchar(50) unique, GOODS_NAME varchar(100), GOODS_TYPE varchar(50), QUANTITY bigint, UNIT_PRICE double precision, AMOUNT double precision, CUSTOMER_NAME varchar(50), CUSTOMER_MOBILE varchar(30), CUSTOMER_PHONE_FAX varchar(30), CUSTOMER_ADDRESS varchar(150), STATE varchar(15), PAYED_TIME datetime, DELIVERED_TIME datetime, primary key (ID));
create table T_FF_RT_TASKINSTANCE (ID varchar(50) not null, BIZ_TYPE varchar(250) not null, TASK_ID text not null, ACTIVITY_ID varchar(200) not null, NAME varchar(100) not null, DISPLAY_NAME varchar(128), STATE integer not null, SUSPENDED bit not null, TASK_TYPE varchar(10), CREATED_TIME datetime not null, STARTED_TIME datetime, EXPIRED_TIME datetime, END_TIME datetime, ASSIGNMENT_STRATEGY varchar(10), PROCESSINSTANCE_ID varchar(50) not null, PROCESS_ID varchar(100) not null, VERSION integer not null, TARGET_ACTIVITY_ID varchar(100), FROM_ACTIVITY_ID text, STEP_NUMBER integer not null, CAN_BE_WITHDRAWN bit not null, primary key (ID));
create table T_SECU_DEPARTMENT (ID varchar(50) not null, CODE varchar(50) not null unique, NAME varchar(100) not null, PARENT_CODE varchar(50) not null, DESCRIPTION text, primary key (ID));
create table T_SECU_RESOURCE (ID varchar(50) not null, CODE varchar(50) not null unique, NAME varchar(100) not null, TYPE varchar(2) not null, VALUE text, PARENT_CODE varchar(50) not null, SORT bigint, MENU_FLAG varchar(10), primary key (ID));
create table T_SECU_ROLE (ID varchar(50) not null, CODE varchar(50) not null unique, NAME varchar(100) not null, DESCRIPTION text, DEPARTMENT_CODE varchar(50) not null, DEPARTMENT_NAME varchar(100), primary key (ID));
create table T_SECU_ROLE_RESOURCE (ID varchar(50) not null, ROLE_CODE varchar(50) not null, RESOURCE_CODE varchar(50) not null, primary key (ID));
create table T_SECU_USER (ID varchar(50) not null, LOGINID varchar(50) not null unique, PASSWORD varchar(128) not null, NAME varchar(50) not null, DISABLED bit not null, ACCOUNT_LOCKED bit not null, ACCOUNT_EXPIRED_TIME datetime, PASSWORD_EXPIRED_TIME datetime, EMAIL varchar(64), DEPARTMENT_CODE varchar(50) not null, DEPARTMENT_NAME varchar(100), TITLE varchar(50), primary key (ID));
create table T_SECU_USER_ROLE (ID varchar(50) not null, LOGINID varchar(50) not null, ROLE_CODE varchar(50) not null, primary key (ID));
alter table T_BIZ_GD_TASKINSTANCE add index FKF0F6F985D06C779D (TASKINSTANCE_ID), add constraint FKF0F6F985D06C779D foreign key (TASKINSTANCE_ID) references T_FF_RT_TASKINSTANCE (ID);
alter table T_BIZ_LOAN_TASKINSTANCE add index FKCBD3CE1240A045E2 (TASKINSTANCE_ID), add constraint FKCBD3CE1240A045E2 foreign key (TASKINSTANCE_ID) references T_FF_RT_TASKINSTANCE (ID);
