drop table T_Biz_EmailMock cascade constraints;
drop table T_Biz_LeaveApplicationInfo cascade constraints;
drop table T_Biz_LeaveApprovalInfo cascade constraints;
drop table T_FF_RT_TASKINSTANCE cascade constraints;
create table T_Biz_EmailMock (ID varchar2(50 char) not null, user_Id varchar2(50 char) not null, content varchar2(512 char) not null, create_Time timestamp not null, primary key (ID));
create table T_Biz_LeaveApplicationInfo (ID varchar2(50 char) not null, sn varchar2(50 char) not null unique, leaveReason varchar2(50 char), fromDate varchar2(50 char), toDate varchar2(50 char), leaveDays number(10,0), applicant_Id varchar2(50 char), applicant_Name varchar2(50 char), submitTime varchar2(50 char), approval_Flag number(1,0), approval_Detail varchar2(50 char), approver varchar2(50 char), approval_Time timestamp, primary key (ID));
create table T_Biz_LeaveApprovalInfo (ID varchar2(50 char) not null, sn varchar2(50 char) not null, approver varchar2(50 char), approval_Flag number(1,0), detail varchar2(100 char), approval_Time timestamp, primary key (ID));
create table T_FF_RT_TASKINSTANCE (ID varchar2(50 char) not null, BIZ_TYPE varchar2(250 char) not null, TASK_ID varchar2(300 char) not null, ACTIVITY_ID varchar2(200 char) not null, NAME varchar2(100 char) not null, DISPLAY_NAME varchar2(128 char), STATE number(10,0) not null, SUSPENDED number(1,0) not null, TASK_TYPE varchar2(10 char), CREATED_TIME timestamp not null, STARTED_TIME timestamp, EXPIRED_TIME timestamp, END_TIME timestamp, ASSIGNMENT_STRATEGY varchar2(10 char), PROCESSINSTANCE_ID varchar2(50 char) not null, PROCESS_ID varchar2(100 char) not null, VERSION number(10,0) not null, TARGET_ACTIVITY_ID varchar2(100 char), FROM_ACTIVITY_ID varchar2(600 char), STEP_NUMBER number(10,0) not null, CAN_BE_WITHDRAWN number(1,0) not null, primary key (ID));
comment on column T_FF_RT_TASKINSTANCE.TASK_ID is '任务id';
comment on column T_FF_RT_TASKINSTANCE.ACTIVITY_ID is '环节id';
comment on column T_FF_RT_TASKINSTANCE.NAME is '名称';
comment on column T_FF_RT_TASKINSTANCE.DISPLAY_NAME is '名称';
comment on column T_FF_RT_TASKINSTANCE.STATE is '状态';
comment on column T_FF_RT_TASKINSTANCE.SUSPENDED is '是否挂起';
comment on column T_FF_RT_TASKINSTANCE.TASK_TYPE is '任务类型,FormTask,ToolTask,SubflowTask';
comment on column T_FF_RT_TASKINSTANCE.CREATED_TIME is '创建时间';
comment on column T_FF_RT_TASKINSTANCE.STARTED_TIME is '启动时间';
comment on column T_FF_RT_TASKINSTANCE.EXPIRED_TIME is '到期时间';
comment on column T_FF_RT_TASKINSTANCE.END_TIME is '终止时间';
comment on column T_FF_RT_TASKINSTANCE.ASSIGNMENT_STRATEGY is 'WorkItem分配策略,取值ALL,ANY';
comment on column T_FF_RT_TASKINSTANCE.PROCESSINSTANCE_ID is '流程实例id';
comment on column T_FF_RT_TASKINSTANCE.PROCESS_ID is '流程id';
comment on column T_FF_RT_TASKINSTANCE.VERSION is '流程版本号';
comment on column T_FF_RT_TASKINSTANCE.TARGET_ACTIVITY_ID is '后续activity的id';
comment on column T_FF_RT_TASKINSTANCE.FROM_ACTIVITY_ID is '前驱activity的id';
comment on column T_FF_RT_TASKINSTANCE.STEP_NUMBER is '步数';
comment on column T_FF_RT_TASKINSTANCE.CAN_BE_WITHDRAWN is '是否可以被撤销';
create index idx_taskInst_stepNb on T_FF_RT_TASKINSTANCE (STEP_NUMBER);
