alter table T_BIZ_GD_TASKINSTANCE drop constraint FKF0F6F985D06C779D;
alter table T_BIZ_LOAN_TASKINSTANCE drop constraint FKCBD3CE1240A045E2;
drop table T_BIZ_GD_TASKINSTANCE;
drop table T_BIZ_LOANINFO;
drop table T_BIZ_LOAN_APPROVEINFO;
drop table T_BIZ_LOAN_TASKINSTANCE;
drop table T_Biz_TradeInfo;
drop table T_FF_RT_TASKINSTANCE;
drop table T_SECU_DEPARTMENT;
drop table T_SECU_RESOURCE;
drop table T_SECU_ROLE;
drop table T_SECU_ROLE_RESOURCE;
drop table T_SECU_USER;
drop table T_SECU_USER_ROLE;
create table T_BIZ_GD_TASKINSTANCE (TASKINSTANCE_ID varchar(50) not null, SN varchar(255) null, GOODS_NAME varchar(255) null, QUANTITY numeric(19,0) null, CUSTOMER_NAME varchar(255) null, primary key (TASKINSTANCE_ID));
create table T_BIZ_LOANINFO (ID varchar(50) not null, SN varchar(50) not null unique, APPLICANT_NAME varchar(50) not null, APPLICANT_ID varchar(50) not null, ADDRESS varchar(256) not null, SALARY int not null, LOAN_VALUE int not null, RETURN_DATE varchar(10) not null, LOANTELLER varchar(50) not null, APP_INFO_INPUT_DATE datetime not null, SALARY_IS_REAL tinyint null, CREDIT_STATUS tinyint null, RISK_FLAG tinyint null, RISK_EVALUATOR varchar(50) null, RISK_INFO_INPUT_DATE datetime null, DECISION tinyint null, examinerList varchar(128) null, approverList varchar(128) null, opponentList varchar(128) null, LEND_MONEY_INFO varchar(256) null, LEND_MONEY_OFFICER varchar(50) null, LEND_MONEY_INFO_INPUT_TIME datetime null, REJECT_INFO varchar(256) null, REJECT_INFO_INPUT_TIME datetime null, primary key (ID));
create table T_BIZ_LOAN_APPROVEINFO (ID varchar(50) not null, SN varchar(50) not null, approver varchar(50) not null, decision tinyint null, detail varchar(50) null, primary key (ID));
create table T_BIZ_LOAN_TASKINSTANCE (TASKINSTANCE_ID varchar(50) not null, SN varchar(255) null, APPLICANT_NAME varchar(255) null, LOAN_VALUE int null, RISK_FLAG tinyint null, DECISION tinyint null, primary key (TASKINSTANCE_ID));
create table T_Biz_TradeInfo (ID varchar(50) not null, SN varchar(50) null unique, GOODS_NAME varchar(100) null, GOODS_TYPE varchar(50) null, QUANTITY numeric(19,0) null, UNIT_PRICE double precision null, AMOUNT double precision null, CUSTOMER_NAME varchar(50) null, CUSTOMER_MOBILE varchar(30) null, CUSTOMER_PHONE_FAX varchar(30) null, CUSTOMER_ADDRESS varchar(150) null, STATE varchar(15) null, PAYED_TIME datetime null, DELIVERED_TIME datetime null, primary key (ID));
create table T_FF_RT_TASKINSTANCE (ID varchar(50) not null, BIZ_TYPE varchar(250) not null, TASK_ID varchar(300) not null, ACTIVITY_ID varchar(200) not null, NAME varchar(100) not null, DISPLAY_NAME varchar(128) null, STATE int not null, SUSPENDED tinyint not null, TASK_TYPE varchar(10) null, CREATED_TIME datetime not null, STARTED_TIME datetime null, EXPIRED_TIME datetime null, END_TIME datetime null, ASSIGNMENT_STRATEGY varchar(10) null, PROCESSINSTANCE_ID varchar(50) not null, PROCESS_ID varchar(100) not null, VERSION int not null, TARGET_ACTIVITY_ID varchar(100) null, FROM_ACTIVITY_ID varchar(600) null, STEP_NUMBER int not null, CAN_BE_WITHDRAWN tinyint not null, primary key (ID));
create table T_SECU_DEPARTMENT (ID varchar(50) not null, CODE varchar(50) not null unique, NAME varchar(100) not null, PARENT_CODE varchar(50) not null, DESCRIPTION varchar(256) null, primary key (ID));
create table T_SECU_RESOURCE (ID varchar(50) not null, CODE varchar(50) not null unique, NAME varchar(100) not null, TYPE varchar(2) not null, VALUE varchar(256) null, PARENT_CODE varchar(50) not null, SORT numeric(19,0) null, MENU_FLAG varchar(10) null, primary key (ID));
create table T_SECU_ROLE (ID varchar(50) not null, CODE varchar(50) not null unique, NAME varchar(100) not null, DESCRIPTION varchar(256) null, DEPARTMENT_CODE varchar(50) not null, DEPARTMENT_NAME varchar(100) null, primary key (ID));
create table T_SECU_ROLE_RESOURCE (ID varchar(50) not null, ROLE_CODE varchar(50) not null, RESOURCE_CODE varchar(50) not null, primary key (ID));
create table T_SECU_USER (ID varchar(50) not null, LOGINID varchar(50) not null unique, PASSWORD varchar(128) not null, NAME varchar(50) not null, DISABLED tinyint not null, ACCOUNT_LOCKED tinyint not null, ACCOUNT_EXPIRED_TIME datetime null, PASSWORD_EXPIRED_TIME datetime null, EMAIL varchar(64) null, DEPARTMENT_CODE varchar(50) not null, DEPARTMENT_NAME varchar(100) null, TITLE varchar(50) null, primary key (ID));
create table T_SECU_USER_ROLE (ID varchar(50) not null, LOGINID varchar(50) not null, ROLE_CODE varchar(50) not null, primary key (ID));
alter table T_BIZ_GD_TASKINSTANCE add constraint FKF0F6F985D06C779D foreign key (TASKINSTANCE_ID) references T_FF_RT_TASKINSTANCE;
alter table T_BIZ_LOAN_TASKINSTANCE add constraint FKCBD3CE1240A045E2 foreign key (TASKINSTANCE_ID) references T_FF_RT_TASKINSTANCE;
